import { Job, Candidate, CandidateApplication, PipelineStage } from './types';

// Realistic dummy data for Recruitment module

export const jobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Full Stack Engineer',
    clientId: 'client-1',
    clientName: 'TechCorp Industries',
    status: 'open',
    priority: 'high',
    roleType: 'tech',
    location: 'Remote (US timezone)',
    contractType: 'full-time',
    startDate: '2025-03-01',
    salaryRange: '$140k - $180k',
    description: 'We are seeking a Senior Full Stack Engineer to join our platform team. You will be responsible for building scalable web applications using React, Node.js, and PostgreSQL.',
    keyRequirements: [
      '5+ years full stack development',
      'React and Node.js expertise',
      'Experience with microservices',
      'Strong communication skills',
    ],
    assignedRecruiterId: 'rec-1',
    assignedRecruiterName: 'Sarah Chen',
    daysOpen: 12,
    sla: 30,
    createdAt: '2025-01-14T10:00:00Z',
    projectId: 'proj-1',
    projectName: 'Platform Modernization',
    candidateCounts: {
      new: 3,
      screening: 2,
      interview: 4,
      clientReview: 2,
      offer: 1,
      placed: 0,
      rejected: 3,
    },
  },
  {
    id: 'job-2',
    title: 'Product Manager - AI/ML',
    clientId: 'client-2',
    clientName: 'DataFlow Analytics',
    status: 'open',
    priority: 'high',
    roleType: 'product',
    location: 'San Francisco, CA (Hybrid)',
    contractType: 'full-time',
    startDate: '2025-02-15',
    salaryRange: '$150k - $190k',
    description: 'Lead product strategy for our AI-powered analytics platform. Define roadmap, work with engineering and design teams.',
    keyRequirements: [
      '3-5 years product management',
      'AI/ML product experience',
      'B2B SaaS background',
      'Data-driven decision making',
    ],
    assignedRecruiterId: 'rec-2',
    assignedRecruiterName: 'Michael Torres',
    daysOpen: 8,
    sla: 30,
    createdAt: '2025-01-18T09:00:00Z',
    candidateCounts: {
      new: 2,
      screening: 3,
      interview: 2,
      clientReview: 1,
      offer: 0,
      placed: 0,
      rejected: 2,
    },
  },
  {
    id: 'job-3',
    title: 'Data Engineer',
    clientId: 'client-2',
    clientName: 'DataFlow Analytics',
    status: 'open',
    priority: 'medium',
    roleType: 'data',
    location: 'Remote (Global)',
    contractType: 'contract',
    startDate: '2025-03-15',
    salaryRange: '$120k - $150k',
    description: 'Build and maintain data pipelines, ETL processes, and data warehouse infrastructure.',
    keyRequirements: [
      'Python and SQL expertise',
      'Experience with Airflow or similar',
      'AWS or GCP data services',
      'Data modeling skills',
    ],
    assignedRecruiterId: 'rec-1',
    assignedRecruiterName: 'Sarah Chen',
    daysOpen: 15,
    sla: 45,
    createdAt: '2025-01-11T14:00:00Z',
    candidateCounts: {
      new: 1,
      screening: 2,
      interview: 1,
      clientReview: 0,
      offer: 0,
      placed: 0,
      rejected: 4,
    },
  },
  {
    id: 'job-4',
    title: 'Senior Product Designer',
    clientId: 'client-3',
    clientName: 'FinanceHub Solutions',
    status: 'open',
    priority: 'medium',
    roleType: 'design',
    location: 'London, UK',
    contractType: 'full-time',
    startDate: '2025-04-01',
    salaryRange: '£70k - £95k',
    description: 'Design delightful user experiences for our fintech platform. Lead design system and collaborate with product and engineering.',
    keyRequirements: [
      '5+ years product design',
      'Fintech or B2B SaaS experience',
      'Strong design systems knowledge',
      'Figma expertise',
    ],
    assignedRecruiterId: 'rec-3',
    assignedRecruiterName: 'Emma Rodriguez',
    daysOpen: 6,
    sla: 30,
    createdAt: '2025-01-20T11:00:00Z',
    candidateCounts: {
      new: 4,
      screening: 1,
      interview: 2,
      clientReview: 0,
      offer: 0,
      placed: 0,
      rejected: 1,
    },
  },
  {
    id: 'job-5',
    title: 'Machine Learning Engineer',
    clientId: 'client-1',
    clientName: 'TechCorp Industries',
    status: 'open',
    priority: 'high',
    roleType: 'tech',
    location: 'Remote (Europe)',
    contractType: 'full-time',
    startDate: '2025-02-20',
    salaryRange: '€90k - €120k',
    description: 'Build and deploy ML models for our recommendation engine. Work with large-scale data and production ML systems.',
    keyRequirements: [
      'Python and ML frameworks (PyTorch/TensorFlow)',
      '3+ years ML engineering',
      'Production ML deployment experience',
      'Strong CS fundamentals',
    ],
    assignedRecruiterId: 'rec-2',
    assignedRecruiterName: 'Michael Torres',
    daysOpen: 10,
    sla: 30,
    createdAt: '2025-01-16T08:00:00Z',
    projectId: 'proj-2',
    projectName: 'AI Recommendations',
    candidateCounts: {
      new: 2,
      screening: 3,
      interview: 3,
      clientReview: 1,
      offer: 0,
      placed: 0,
      rejected: 2,
    },
  },
  {
    id: 'job-6',
    title: 'Operations Manager',
    clientId: 'client-4',
    clientName: 'GrowthLabs',
    status: 'open',
    priority: 'low',
    roleType: 'operations',
    location: 'Austin, TX',
    contractType: 'full-time',
    startDate: '2025-04-15',
    salaryRange: '$90k - $120k',
    description: 'Oversee day-to-day operations, process optimization, and team coordination.',
    keyRequirements: [
      '4+ years operations experience',
      'Process improvement focus',
      'Team management',
      'Tech-savvy',
    ],
    assignedRecruiterId: 'rec-3',
    assignedRecruiterName: 'Emma Rodriguez',
    daysOpen: 4,
    sla: 45,
    createdAt: '2025-01-22T10:00:00Z',
    candidateCounts: {
      new: 3,
      screening: 1,
      interview: 0,
      clientReview: 0,
      offer: 0,
      placed: 0,
      rejected: 0,
    },
  },
  {
    id: 'job-7',
    title: 'DevOps Engineer',
    clientId: 'client-1',
    clientName: 'TechCorp Industries',
    status: 'on-hold',
    priority: 'medium',
    roleType: 'tech',
    location: 'Remote (US)',
    contractType: 'contract',
    startDate: '2025-05-01',
    salaryRange: '$130k - $160k',
    description: 'Build and maintain CI/CD pipelines, infrastructure as code, and cloud infrastructure.',
    keyRequirements: [
      'AWS or GCP expertise',
      'Kubernetes and Docker',
      'Terraform or CloudFormation',
      'CI/CD tools (GitHub Actions, Jenkins)',
    ],
    assignedRecruiterId: 'rec-1',
    assignedRecruiterName: 'Sarah Chen',
    daysOpen: 20,
    sla: 45,
    createdAt: '2025-01-06T09:00:00Z',
    candidateCounts: {
      new: 1,
      screening: 0,
      interview: 0,
      clientReview: 0,
      offer: 0,
      placed: 0,
      rejected: 5,
    },
  },
  {
    id: 'job-8',
    title: 'Senior Data Analyst',
    clientId: 'client-2',
    clientName: 'DataFlow Analytics',
    status: 'closed',
    priority: 'medium',
    roleType: 'data',
    location: 'New York, NY',
    contractType: 'full-time',
    startDate: '2025-02-01',
    salaryRange: '$100k - $130k',
    description: 'Analyze data, build dashboards, and provide insights to drive business decisions.',
    keyRequirements: [
      'SQL and Python',
      'Tableau or similar BI tools',
      'Statistical analysis',
      'Business acumen',
    ],
    assignedRecruiterId: 'rec-2',
    assignedRecruiterName: 'Michael Torres',
    daysOpen: 28,
    sla: 30,
    createdAt: '2024-12-29T10:00:00Z',
    candidateCounts: {
      new: 0,
      screening: 0,
      interview: 0,
      clientReview: 0,
      offer: 0,
      placed: 1,
      rejected: 8,
    },
  },
  {
    id: 'job-9',
    title: 'Frontend Engineer (React)',
    clientId: 'client-3',
    clientName: 'FinanceHub Solutions',
    status: 'closed',
    priority: 'high',
    roleType: 'tech',
    location: 'Remote (UK)',
    contractType: 'full-time',
    startDate: '2025-01-15',
    salaryRange: '£60k - £85k',
    description: 'Build beautiful, performant frontend applications using React and TypeScript.',
    keyRequirements: [
      'React and TypeScript',
      'Modern CSS (Tailwind, CSS-in-JS)',
      'Testing (Jest, RTL)',
      'Performance optimization',
    ],
    assignedRecruiterId: 'rec-3',
    assignedRecruiterName: 'Emma Rodriguez',
    daysOpen: 22,
    sla: 30,
    createdAt: '2024-12-24T08:00:00Z',
    candidateCounts: {
      new: 0,
      screening: 0,
      interview: 0,
      clientReview: 0,
      offer: 0,
      placed: 1,
      rejected: 12,
    },
  },
  {
    id: 'job-10',
    title: 'Product Marketing Manager',
    clientId: 'client-4',
    clientName: 'GrowthLabs',
    status: 'open',
    priority: 'medium',
    roleType: 'product',
    location: 'Remote (Global)',
    contractType: 'full-time',
    startDate: '2025-03-10',
    salaryRange: '$110k - $140k',
    description: 'Drive go-to-market strategy, positioning, and product messaging.',
    keyRequirements: [
      '3-5 years product marketing',
      'B2B SaaS experience',
      'Strong storytelling',
      'Data-driven approach',
    ],
    assignedRecruiterId: 'rec-1',
    assignedRecruiterName: 'Sarah Chen',
    daysOpen: 7,
    sla: 30,
    createdAt: '2025-01-19T12:00:00Z',
    candidateCounts: {
      new: 2,
      screening: 2,
      interview: 1,
      clientReview: 1,
      offer: 0,
      placed: 0,
      rejected: 1,
    },
  },
];

export const candidates: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Alex Thompson',
    email: 'alex.thompson@email.com',
    phone: '+1 555-0101',
    location: 'Seattle, WA',
    currentRole: 'Senior Software Engineer at Amazon',
    availability: 'Immediate',
    source: 'linkedin',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'PostgreSQL', 'Docker'],
    experienceYears: 6,
    cvUrl: '/docs/alex-thompson-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/alexthompson',
    createdAt: '2025-01-15T10:00:00Z',
    lastActivity: '2025-01-24T14:30:00Z',
    applications: [],
    aiSummary: 'Strong full-stack engineer with proven track record at FAANG company. Deep expertise in React and Node.js with AWS cloud infrastructure.',
    aiFitScore: 92,
    aiSuggestedQuestions: [
      'Can you describe your experience with microservices architecture?',
      'How do you approach system design for scalable applications?',
      'Tell me about a challenging technical problem you solved recently.',
    ],
  },
  {
    id: 'cand-2',
    name: 'Maria Rodriguez',
    email: 'maria.rodriguez@email.com',
    phone: '+1 555-0102',
    location: 'Austin, TX',
    currentRole: 'Product Manager at Stripe',
    availability: '2 weeks notice',
    source: 'referral',
    skills: ['Product Strategy', 'AI/ML Products', 'Data Analytics', 'Roadmapping', 'Agile'],
    experienceYears: 5,
    cvUrl: '/docs/maria-rodriguez-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/mariarodriguez',
    portfolioUrl: 'https://mariarodriguez.com',
    createdAt: '2025-01-18T11:00:00Z',
    lastActivity: '2025-01-25T09:15:00Z',
    applications: [],
    aiSummary: 'Exceptional product leader with strong AI/ML background. Successfully launched multiple B2B products at scale.',
    aiFitScore: 95,
    aiSuggestedQuestions: [
      'How do you balance user needs with business objectives?',
      'Describe your experience launching AI-powered features.',
      'How do you measure product success?',
    ],
  },
  {
    id: 'cand-3',
    name: 'James Chen',
    email: 'james.chen@email.com',
    phone: '+1 555-0103',
    location: 'San Francisco, CA',
    currentRole: 'Data Engineer at Snowflake',
    availability: '1 month notice',
    source: 'direct-application',
    skills: ['Python', 'SQL', 'Airflow', 'Spark', 'AWS', 'Data Modeling'],
    experienceYears: 4,
    cvUrl: '/docs/james-chen-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/jameschen',
    createdAt: '2025-01-12T09:00:00Z',
    lastActivity: '2025-01-23T16:45:00Z',
    applications: [],
    aiSummary: 'Solid data engineering experience with modern data stack. Strong SQL and Python skills.',
    aiFitScore: 85,
  },
  {
    id: 'cand-4',
    name: 'Sophie Anderson',
    email: 'sophie.anderson@email.com',
    phone: '+44 20 1234 5678',
    location: 'London, UK',
    currentRole: 'Senior Product Designer at Monzo',
    availability: 'Immediate',
    source: 'recruiter-outreach',
    skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping', 'B2B SaaS'],
    experienceYears: 7,
    cvUrl: '/docs/sophie-anderson-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/sophieanderson',
    portfolioUrl: 'https://sophieanderson.design',
    createdAt: '2025-01-20T13:00:00Z',
    lastActivity: '2025-01-25T11:00:00Z',
    applications: [],
    aiSummary: 'Exceptional designer with strong fintech background. Led design system initiatives at scale.',
    aiFitScore: 94,
  },
  {
    id: 'cand-5',
    name: 'David Kim',
    email: 'david.kim@email.com',
    phone: '+1 555-0105',
    location: 'Remote (California)',
    currentRole: 'ML Engineer at Google',
    availability: '3 weeks notice',
    source: 'linkedin',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'MLOps', 'Kubernetes', 'GCP'],
    experienceYears: 5,
    cvUrl: '/docs/david-kim-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/davidkim',
    createdAt: '2025-01-16T10:00:00Z',
    lastActivity: '2025-01-24T13:20:00Z',
    applications: [],
    aiSummary: 'World-class ML engineer with production ML systems experience at FAANG. Strong fundamentals.',
    aiFitScore: 96,
  },
];

export const candidateApplications: CandidateApplication[] = [
  // Alex Thompson - Senior Full Stack Engineer
  {
    id: 'app-1',
    jobId: 'job-1',
    jobTitle: 'Senior Full Stack Engineer',
    candidateId: 'cand-1',
    stage: 'interview',
    appliedAt: '2025-01-15T10:00:00Z',
    lastUpdated: '2025-01-24T14:30:00Z',
    recruiterNotes: [
      {
        id: 'note-1',
        authorId: 'rec-1',
        authorName: 'Sarah Chen',
        content: 'Strong technical skills. Passed coding interview with flying colors. Team fit looks good.',
        createdAt: '2025-01-22T15:00:00Z',
      },
    ],
    clientFeedback: [],
  },
  // Maria Rodriguez - Product Manager AI/ML
  {
    id: 'app-2',
    jobId: 'job-2',
    jobTitle: 'Product Manager - AI/ML',
    candidateId: 'cand-2',
    stage: 'client-review',
    appliedAt: '2025-01-18T11:00:00Z',
    lastUpdated: '2025-01-25T09:15:00Z',
    recruiterNotes: [
      {
        id: 'note-2',
        authorId: 'rec-2',
        authorName: 'Michael Torres',
        content: 'Excellent product sense. Strong AI/ML background. Client will love her.',
        createdAt: '2025-01-24T10:00:00Z',
      },
    ],
    clientFeedback: [],
  },
  // James Chen - Data Engineer
  {
    id: 'app-3',
    jobId: 'job-3',
    jobTitle: 'Data Engineer',
    candidateId: 'cand-3',
    stage: 'screening',
    appliedAt: '2025-01-12T09:00:00Z',
    lastUpdated: '2025-01-23T16:45:00Z',
    recruiterNotes: [],
    clientFeedback: [],
  },
  // Sophie Anderson - Senior Product Designer
  {
    id: 'app-4',
    jobId: 'job-4',
    jobTitle: 'Senior Product Designer',
    candidateId: 'cand-4',
    stage: 'interview',
    appliedAt: '2025-01-20T13:00:00Z',
    lastUpdated: '2025-01-25T11:00:00Z',
    recruiterNotes: [
      {
        id: 'note-3',
        authorId: 'rec-3',
        authorName: 'Emma Rodriguez',
        content: 'Portfolio is stunning. Great cultural fit. Moving to final round.',
        createdAt: '2025-01-24T14:00:00Z',
      },
    ],
    clientFeedback: [],
  },
  // David Kim - ML Engineer
  {
    id: 'app-5',
    jobId: 'job-5',
    jobTitle: 'Machine Learning Engineer',
    candidateId: 'cand-5',
    stage: 'offer',
    appliedAt: '2025-01-16T10:00:00Z',
    lastUpdated: '2025-01-24T13:20:00Z',
    recruiterNotes: [
      {
        id: 'note-4',
        authorId: 'rec-2',
        authorName: 'Michael Torres',
        content: 'Top candidate. Client approved. Preparing offer.',
        createdAt: '2025-01-24T13:00:00Z',
      },
    ],
    clientFeedback: [
      {
        id: 'feedback-1',
        contactName: 'John Smith (CTO)',
        rating: 'positive',
        feedback: 'Exceptional candidate. Let\'s move fast on this one.',
        createdAt: '2025-01-23T16:00:00Z',
      },
    ],
  },
];
