import { User, Task, Approval, Issue, Comment, ActivityEntry } from './types';

// Users
export const users: User[] = [
  { id: '1', name: 'Sarah Chen', avatar: 'SC', email: 'sarah.chen@company.com' },
  { id: '2', name: 'Marcus Johnson', avatar: 'MJ', email: 'marcus.j@company.com' },
  { id: '3', name: 'Emma Rodriguez', avatar: 'ER', email: 'emma.r@company.com' },
  { id: '4', name: 'David Kim', avatar: 'DK', email: 'david.kim@company.com' },
  { id: '5', name: 'Lisa Park', avatar: 'LP', email: 'lisa.park@company.com' },
  { id: '6', name: 'Michael Torres', avatar: 'MT', email: 'michael.t@company.com' },
  { id: '7', name: 'Rachel Green', avatar: 'RG', email: 'rachel.g@company.com' },
];

// Sample comments for reuse
const sampleComments: Comment[] = [
  {
    id: 'c1',
    userId: '2',
    text: 'I\'ve started working on this. Should have an update by EOD.',
    timestamp: '2026-01-24T14:30:00Z',
  },
  {
    id: 'c2',
    userId: '1',
    text: 'Great! Let me know if you need any additional resources.',
    timestamp: '2026-01-24T15:45:00Z',
  },
  {
    id: 'c3',
    userId: '3',
    text: 'I can help with the technical review once ready.',
    timestamp: '2026-01-25T09:15:00Z',
  },
];

const sampleActivity: ActivityEntry[] = [
  {
    id: 'a1',
    userId: '1',
    action: 'created',
    timestamp: '2026-01-20T10:00:00Z',
  },
  {
    id: 'a2',
    userId: 'ai',
    action: 'assigned',
    timestamp: '2026-01-20T10:05:00Z',
    details: 'Auto-assigned based on workload analysis',
  },
  {
    id: 'a3',
    userId: '2',
    action: 'status_changed',
    timestamp: '2026-01-23T14:20:00Z',
    details: 'Changed from To Do to In Progress',
  },
];

// Tasks with realistic dummy data
export const tasks: Task[] = [
  // Overdue tasks
  {
    id: 't1',
    title: 'Complete security audit report for Global Dynamics',
    description: 'Finalize the comprehensive security assessment and submit recommendations to the client.',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-01-22',
    entityType: 'project',
    entityId: 'p2',
    entityName: 'Security Audit & Compliance',
    assigneeId: '2',
    createdById: '1',
    source: 'manual',
    isOverdue: true,
    comments: sampleComments.slice(0, 2),
    activityLog: sampleActivity,
  },
  {
    id: 't2',
    title: 'Review and approve candidate background check',
    description: 'Complete the background verification process for Alex Turner before final offer.',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-01-23',
    entityType: 'candidate',
    entityId: 'cd1',
    entityName: 'Alex Turner - Senior Full-Stack Engineer',
    assigneeId: '5',
    createdById: '1',
    source: 'ai',
    isOverdue: true,
    comments: [],
    activityLog: sampleActivity.slice(0, 2),
  },
  {
    id: 't3',
    title: 'Update client on project timeline delays',
    description: 'Prepare and send communication about the 2-week delay in Phase 2 deliverables.',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-01-24',
    entityType: 'client',
    entityId: 'c1',
    entityName: 'TechVenture Labs',
    assigneeId: '1',
    createdById: '1',
    source: 'email',
    isOverdue: true,
    comments: sampleComments,
    activityLog: sampleActivity,
  },
  {
    id: 't4',
    title: 'Schedule follow-up interview with Nina Patel',
    description: 'Coordinate calendars for final client interview round.',
    status: 'waiting',
    priority: 'medium',
    dueDate: '2026-01-23',
    entityType: 'candidate',
    entityId: 'cd2',
    entityName: 'Nina Patel - Product Designer',
    assigneeId: '5',
    createdById: '3',
    source: 'meeting',
    isOverdue: true,
    comments: [],
    activityLog: sampleActivity,
  },

  // Blocked tasks
  {
    id: 't5',
    title: 'Deploy API integration to production',
    description: 'Waiting for client infrastructure access and security clearance.',
    status: 'blocked',
    priority: 'high',
    dueDate: '2026-01-27',
    entityType: 'project',
    entityId: 'p7',
    entityName: 'API Integration Suite',
    assigneeId: '4',
    createdById: '2',
    source: 'manual',
    isOverdue: false,
    comments: sampleComments.slice(0, 2),
    activityLog: sampleActivity,
  },
  {
    id: 't6',
    title: 'Review mobile app wireframes',
    description: 'Client requested design changes - waiting for updated mockups from design team.',
    status: 'blocked',
    priority: 'medium',
    dueDate: '2026-01-28',
    entityType: 'project',
    entityId: 'p3',
    entityName: 'Mobile App Redesign',
    assigneeId: '3',
    createdById: '1',
    source: 'email',
    isOverdue: false,
    comments: sampleComments,
    activityLog: sampleActivity,
  },
  {
    id: 't7',
    title: 'Configure DevOps pipeline',
    description: 'Blocked on infrastructure procurement approval.',
    status: 'blocked',
    priority: 'medium',
    dueDate: '2026-01-29',
    entityType: 'project',
    entityId: 'p8',
    entityName: 'DevOps Automation',
    assigneeId: '4',
    createdById: '2',
    source: 'manual',
    isOverdue: false,
    comments: [],
    activityLog: sampleActivity,
  },

  // Today's tasks
  {
    id: 't8',
    title: 'Prepare Q1 analytics report',
    description: 'Compile data visualization and insights for executive review.',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-01-26',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '6',
    createdById: '1',
    source: 'ai',
    isOverdue: false,
    comments: sampleComments.slice(0, 1),
    activityLog: sampleActivity,
  },
  {
    id: 't9',
    title: 'Review pull request for authentication module',
    description: 'Code review needed for new OAuth implementation.',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-01-26',
    entityType: 'project',
    entityId: 'p2',
    entityName: 'AI Platform Development',
    assigneeId: '4',
    createdById: '2',
    source: 'ai',
    isOverdue: false,
    comments: [],
    activityLog: sampleActivity,
  },
  {
    id: 't10',
    title: 'Update project status dashboard',
    description: 'Refresh all project metrics and KPIs for weekly stakeholder meeting.',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-01-26',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '1',
    createdById: '1',
    source: 'meeting',
    isOverdue: false,
    comments: sampleComments,
    activityLog: sampleActivity,
  },

  // Tomorrow and this week
  {
    id: 't11',
    title: 'Conduct technical interview with candidate',
    description: 'Interview Alex Turner for Senior Full-Stack Engineer position.',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-01-27',
    entityType: 'job',
    entityId: 'j1',
    entityName: 'Senior Full-Stack Engineer',
    assigneeId: '2',
    createdById: '5',
    source: 'manual',
    isOverdue: false,
    comments: [],
    activityLog: sampleActivity,
  },
  {
    id: 't12',
    title: 'Create data migration plan',
    description: 'Document strategy for moving client data to new cloud infrastructure.',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-01-27',
    entityType: 'project',
    entityId: 'p1',
    entityName: 'Cloud Migration Phase 2',
    assigneeId: '4',
    createdById: '1',
    source: 'manual',
    isOverdue: false,
    comments: sampleComments.slice(0, 2),
    activityLog: sampleActivity,
  },
  {
    id: 't13',
    title: 'Update contract terms document',
    description: 'Revise SOW based on client feedback from last week\'s meeting.',
    status: 'in-progress',
    priority: 'medium',
    dueDate: '2026-01-28',
    entityType: 'client',
    entityId: 'c4',
    entityName: 'Quantum Systems',
    assigneeId: '7',
    createdById: '1',
    source: 'email',
    isOverdue: false,
    comments: [],
    activityLog: sampleActivity,
  },
  {
    id: 't14',
    title: 'Design database schema for analytics module',
    description: 'Create ERD and define table structures for new analytics features.',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-01-28',
    entityType: 'project',
    entityId: 'p4',
    entityName: 'Data Analytics Dashboard',
    assigneeId: '4',
    createdById: '2',
    source: 'manual',
    isOverdue: false,
    comments: sampleComments,
    activityLog: sampleActivity,
  },
  {
    id: 't15',
    title: 'Test payment integration in staging',
    description: 'Complete QA for Stripe payment flow before production release.',
    status: 'waiting',
    priority: 'medium',
    dueDate: '2026-01-29',
    entityType: 'project',
    entityId: 'p6',
    entityName: 'E-commerce Platform',
    assigneeId: '3',
    createdById: '2',
    source: 'ai',
    isOverdue: false,
    comments: [],
    activityLog: sampleActivity,
  },
  {
    id: 't16',
    title: 'Write API documentation',
    description: 'Document all endpoints for external developer portal.',
    status: 'in-progress',
    priority: 'low',
    dueDate: '2026-01-29',
    entityType: 'project',
    entityId: 'p7',
    entityName: 'API Integration Suite',
    assigneeId: '6',
    createdById: '4',
    source: 'manual',
    isOverdue: false,
    comments: sampleComments.slice(0, 1),
    activityLog: sampleActivity,
  },
  {
    id: 't17',
    title: 'Prepare onboarding materials for new hire',
    description: 'Compile resources and schedule for Nina Patel\'s first week.',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-01-30',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '5',
    createdById: '1',
    source: 'manual',
    isOverdue: false,
    comments: [],
    activityLog: sampleActivity,
  },
  {
    id: 't18',
    title: 'Update team capacity planning spreadsheet',
    description: 'Reflect latest project assignments and availability for Q1.',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-01-30',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '1',
    createdById: '1',
    source: 'ai',
    isOverdue: false,
    comments: sampleComments,
    activityLog: sampleActivity,
  },
  {
    id: 't19',
    title: 'Create performance optimization checklist',
    description: 'Document best practices for frontend performance improvements.',
    status: 'done',
    priority: 'low',
    dueDate: '2026-01-31',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '3',
    createdById: '2',
    source: 'manual',
    isOverdue: false,
    comments: [],
    activityLog: sampleActivity,
  },
  {
    id: 't20',
    title: 'Schedule quarterly planning session',
    description: 'Coordinate calendars for all department leads for Q2 planning.',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-01-31',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '1',
    createdById: '1',
    source: 'manual',
    isOverdue: false,
    comments: sampleComments,
    activityLog: sampleActivity,
  },
];

// Approvals
export const approvals: Approval[] = [
  // Overdue approvals
  {
    id: 'a1',
    type: 'timesheet',
    title: 'Timesheet - Week of Jan 15-19, 2026',
    description: 'Weekly timesheet submission for Cloud Migration project.',
    requestedById: '2',
    requestedAt: '2026-01-20T09:00:00Z',
    dueDate: '2026-01-23',
    status: 'pending',
    entityType: 'project',
    entityId: 'p1',
    entityName: 'Cloud Migration Phase 2',
    isOverdue: true,
    comments: [],
  },
  {
    id: 'a2',
    type: 'invoice',
    title: 'Invoice #INV-2026-0012',
    description: 'Monthly retainer invoice for Global Dynamics Inc.',
    requestedById: '7',
    requestedAt: '2026-01-19T14:00:00Z',
    dueDate: '2026-01-24',
    status: 'pending',
    entityType: 'client',
    entityId: 'c2',
    entityName: 'Global Dynamics Inc',
    isOverdue: true,
    comments: sampleComments.slice(0, 1),
    documentUrl: '/documents/invoices/INV-2026-0012.pdf',
  },

  // Pending approvals
  {
    id: 'a3',
    type: 'leave',
    title: 'Vacation Request - Feb 10-14, 2026',
    description: 'PTO request for 5 days in February.',
    requestedById: '3',
    requestedAt: '2026-01-25T10:30:00Z',
    dueDate: '2026-01-28',
    status: 'pending',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    isOverdue: false,
    comments: [],
  },
  {
    id: 'a4',
    type: 'document',
    title: 'SOW Amendment - Quantum Systems',
    description: 'Updated statement of work with revised scope and timeline.',
    requestedById: '7',
    requestedAt: '2026-01-25T11:00:00Z',
    dueDate: '2026-01-27',
    status: 'pending',
    entityType: 'client',
    entityId: 'c4',
    entityName: 'Quantum Systems',
    isOverdue: false,
    comments: sampleComments.slice(0, 2),
    documentUrl: '/documents/sow/quantum-amendment.pdf',
  },
  {
    id: 'a5',
    type: 'timesheet',
    title: 'Timesheet - Week of Jan 22-26, 2026',
    description: 'Weekly timesheet submission for API Integration project.',
    requestedById: '4',
    requestedAt: '2026-01-25T16:00:00Z',
    dueDate: '2026-01-29',
    status: 'pending',
    entityType: 'project',
    entityId: 'p7',
    entityName: 'API Integration Suite',
    isOverdue: false,
    comments: [],
  },
  {
    id: 'a6',
    type: 'invoice',
    title: 'Invoice #INV-2026-0015',
    description: 'Project milestone payment for Mobile App Redesign.',
    requestedById: '7',
    requestedAt: '2026-01-26T09:00:00Z',
    dueDate: '2026-01-30',
    status: 'pending',
    entityType: 'project',
    entityId: 'p3',
    entityName: 'Mobile App Redesign',
    isOverdue: false,
    comments: [],
    documentUrl: '/documents/invoices/INV-2026-0015.pdf',
  },

  // Approved
  {
    id: 'a7',
    type: 'document',
    title: 'NDA - Stellar Enterprises',
    description: 'Non-disclosure agreement for new project engagement.',
    requestedById: '1',
    requestedAt: '2026-01-20T10:00:00Z',
    dueDate: '2026-01-25',
    status: 'approved',
    entityType: 'client',
    entityId: 'c6',
    entityName: 'Stellar Enterprises',
    isOverdue: false,
    comments: sampleComments,
    documentUrl: '/documents/nda/stellar-nda.pdf',
  },
  {
    id: 'a8',
    type: 'timesheet',
    title: 'Timesheet - Week of Jan 8-12, 2026',
    description: 'Weekly timesheet submission for DevOps project.',
    requestedById: '4',
    requestedAt: '2026-01-13T17:00:00Z',
    dueDate: '2026-01-17',
    status: 'approved',
    entityType: 'project',
    entityId: 'p8',
    entityName: 'DevOps Automation',
    isOverdue: false,
    comments: [],
  },

  // Rejected
  {
    id: 'a9',
    type: 'leave',
    title: 'Sick Leave - Jan 18, 2026',
    description: 'Sick day request.',
    requestedById: '6',
    requestedAt: '2026-01-18T08:00:00Z',
    dueDate: '2026-01-18',
    status: 'rejected',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    isOverdue: false,
    comments: [
      {
        id: 'c-reject1',
        userId: '1',
        text: 'Please use emergency sick leave process for same-day requests.',
        timestamp: '2026-01-18T09:00:00Z',
      },
    ],
  },
];

// Issues
export const issues: Issue[] = [
  // Critical issues
  {
    id: 'i1',
    title: 'Production API experiencing intermittent timeouts',
    description: 'Users reporting 504 gateway timeout errors on main API endpoints. Affecting approximately 15% of requests during peak hours.',
    severity: 'critical',
    status: 'in-progress',
    entityType: 'project',
    entityId: 'p2',
    entityName: 'AI Platform Development',
    assigneeId: '4',
    createdById: '2',
    createdAt: '2026-01-25T08:00:00Z',
    comments: sampleComments,
    activityLog: [
      {
        id: 'ia1',
        userId: '2',
        action: 'created',
        timestamp: '2026-01-25T08:00:00Z',
        details: 'Issue reported by monitoring system',
      },
      {
        id: 'ia2',
        userId: '4',
        action: 'assigned',
        timestamp: '2026-01-25T08:15:00Z',
      },
      {
        id: 'ia3',
        userId: '4',
        action: 'status_changed',
        timestamp: '2026-01-25T09:30:00Z',
        details: 'Started investigation',
      },
    ],
  },
  {
    id: 'i2',
    title: 'Client cannot access project dashboard',
    description: 'TechVenture Labs reporting authentication failures when trying to access their project portal. All other clients are functioning normally.',
    severity: 'critical',
    status: 'open',
    entityType: 'client',
    entityId: 'c1',
    entityName: 'TechVenture Labs',
    assigneeId: '3',
    createdById: '1',
    createdAt: '2026-01-25T11:30:00Z',
    comments: [],
    activityLog: [
      {
        id: 'ia4',
        userId: '1',
        action: 'created',
        timestamp: '2026-01-25T11:30:00Z',
      },
    ],
  },

  // High severity
  {
    id: 'i3',
    title: 'Mobile app crashing on iOS devices',
    description: 'Beta testers reporting consistent crashes when accessing the profile screen on iOS 17+.',
    severity: 'high',
    status: 'in-progress',
    entityType: 'project',
    entityId: 'p3',
    entityName: 'Mobile App Redesign',
    assigneeId: '3',
    createdById: '5',
    createdAt: '2026-01-24T14:00:00Z',
    comments: sampleComments.slice(0, 2),
    activityLog: sampleActivity,
  },
  {
    id: 'i4',
    title: 'Payment processing delays for invoices',
    description: 'Finance team reporting 2-3 day delays in payment processing through the new system.',
    severity: 'high',
    status: 'open',
    entityType: 'project',
    entityId: 'p6',
    entityName: 'E-commerce Platform',
    assigneeId: '6',
    createdById: '7',
    createdAt: '2026-01-23T10:00:00Z',
    comments: [],
    activityLog: sampleActivity.slice(0, 1),
  },

  // Medium severity
  {
    id: 'i5',
    title: 'Candidate portal - Resume upload size limit too restrictive',
    description: 'Multiple candidates unable to upload portfolio PDFs. Current 2MB limit needs to be increased to at least 5MB.',
    severity: 'medium',
    status: 'open',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '3',
    createdById: '5',
    createdAt: '2026-01-22T09:00:00Z',
    comments: sampleComments.slice(0, 1),
    activityLog: sampleActivity.slice(0, 2),
  },
  {
    id: 'i6',
    title: 'Email notifications not including task links',
    description: 'Users reporting that task notification emails don\'t contain clickable links to the tasks.',
    severity: 'medium',
    status: 'blocked',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '2',
    createdById: '6',
    createdAt: '2026-01-21T15:00:00Z',
    comments: [],
    activityLog: sampleActivity,
  },
  {
    id: 'i7',
    title: 'Dashboard charts not responsive on tablets',
    description: 'Analytics charts overflow container on iPad and similar devices.',
    severity: 'medium',
    status: 'in-progress',
    entityType: 'project',
    entityId: 'p4',
    entityName: 'Data Analytics Dashboard',
    assigneeId: '3',
    createdById: '1',
    createdAt: '2026-01-20T11:00:00Z',
    comments: sampleComments,
    activityLog: sampleActivity,
  },

  // Low severity
  {
    id: 'i8',
    title: 'Typo in onboarding welcome message',
    description: 'Spelling error in the automated welcome email sent to new users.',
    severity: 'low',
    status: 'open',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '7',
    createdById: '5',
    createdAt: '2026-01-19T14:00:00Z',
    comments: [],
    activityLog: sampleActivity.slice(0, 1),
  },
  {
    id: 'i9',
    title: 'Profile avatar upload - file type validation message unclear',
    description: 'Error message when uploading unsupported file types could be more descriptive.',
    severity: 'low',
    status: 'resolved',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '3',
    createdById: '6',
    createdAt: '2026-01-18T10:00:00Z',
    comments: sampleComments,
    activityLog: [...sampleActivity, {
      id: 'ia5',
      userId: '3',
      action: 'status_changed',
      timestamp: '2026-01-19T16:00:00Z',
      details: 'Fixed and deployed',
    }],
  },
  {
    id: 'i10',
    title: 'Knowledge base search returns outdated articles first',
    description: 'Search results not prioritizing recently updated content.',
    severity: 'low',
    status: 'open',
    entityType: 'internal',
    entityId: 'int1',
    entityName: 'Internal Operations',
    assigneeId: '6',
    createdById: '2',
    createdAt: '2026-01-17T13:00:00Z',
    comments: [],
    activityLog: sampleActivity.slice(0, 1),
  },
];
