import { Request, RequestComment, RequestActivity } from './request-types';

// Sample request comments
const sampleRequestComments: RequestComment[] = [
  {
    id: 'rc1',
    userId: '1',
    text: 'Thank you for submitting this request. We\'re reviewing it now.',
    timestamp: '2026-01-24T10:00:00Z',
    isInternal: false,
  },
  {
    id: 'rc2',
    userId: '2',
    text: 'Need to clarify budget before proceeding.',
    timestamp: '2026-01-24T14:30:00Z',
    isInternal: true,
  },
];

const sampleRequestActivity: RequestActivity[] = [
  {
    id: 'ra1',
    userId: 'system',
    action: 'created',
    timestamp: '2026-01-23T09:00:00Z',
  },
  {
    id: 'ra2',
    userId: '1',
    action: 'status_changed',
    timestamp: '2026-01-24T10:00:00Z',
    details: 'Changed from New to In Review',
  },
];

export const requests: Request[] = [
  // Client Requests
  {
    id: 'req-1',
    requestType: 'client',
    category: 'new-talent',
    subject: 'Need Senior Data Engineer for Q2 project',
    description: 'We need to hire a senior data engineer with experience in AWS and Spark for our new analytics platform. Start date should be March 1st.',
    requestedById: 'ext-1',
    requestedByName: 'John Smith',
    requestedByOrg: 'TechVenture Labs',
    submittedDate: '2026-01-20T09:00:00Z',
    dueDate: '2026-02-15T00:00:00Z',
    status: 'in-review',
    ownerId: '5',
    relatedEntityType: 'client',
    relatedEntityId: 'c1',
    relatedEntityName: 'TechVenture Labs',
    comments: sampleRequestComments,
    activityLog: sampleRequestActivity,
  },
  {
    id: 'req-2',
    requestType: 'client',
    category: 'change-request',
    subject: 'Change scope - Add mobile app to Cloud Migration Phase 2',
    description: 'Client wants to include mobile app development in the existing cloud migration project. Estimated to add 3 months to timeline.',
    requestedById: 'ext-2',
    requestedByName: 'Sarah Williams',
    requestedByOrg: 'TechVenture Labs',
    submittedDate: '2026-01-22T14:00:00Z',
    dueDate: '2026-01-27T00:00:00Z',
    status: 'new',
    ownerId: '1',
    relatedEntityType: 'project',
    relatedEntityId: 'p1',
    relatedEntityName: 'Cloud Migration Phase 2',
    comments: [],
    activityLog: sampleRequestActivity.slice(0, 1),
  },
  {
    id: 'req-3',
    requestType: 'client',
    category: 'support',
    subject: 'API Integration - Authentication not working',
    description: 'Getting 401 errors when trying to authenticate with the new API. Need urgent support.',
    requestedById: 'ext-3',
    requestedByName: 'Michael Chen',
    requestedByOrg: 'Global Dynamics Inc',
    submittedDate: '2026-01-25T11:00:00Z',
    dueDate: '2026-01-26T00:00:00Z',
    status: 'in-review',
    ownerId: '4',
    relatedEntityType: 'project',
    relatedEntityId: 'p7',
    relatedEntityName: 'API Integration Suite',
    comments: sampleRequestComments,
    activityLog: sampleRequestActivity,
  },
  {
    id: 'req-4',
    requestType: 'client',
    category: 'other',
    subject: 'Request project status report',
    description: 'Please provide a comprehensive status report for the Mobile App Redesign project for our quarterly board meeting.',
    requestedById: 'ext-4',
    requestedByName: 'Laura Martinez',
    requestedByOrg: 'Innovate Solutions',
    submittedDate: '2026-01-24T16:00:00Z',
    dueDate: '2026-01-29T00:00:00Z',
    status: 'approved',
    ownerId: '3',
    relatedEntityType: 'project',
    relatedEntityId: 'p3',
    relatedEntityName: 'Mobile App Redesign',
    comments: sampleRequestComments.slice(0, 1),
    activityLog: [...sampleRequestActivity, {
      id: 'ra3',
      userId: '1',
      action: 'approved',
      timestamp: '2026-01-25T09:00:00Z',
    }],
  },

  // Employee Requests
  {
    id: 'req-5',
    requestType: 'employee',
    category: 'leave',
    subject: 'Vacation Request - Feb 10-14, 2026',
    description: 'Requesting 5 days PTO for a family trip. All current tasks will be completed before departure.',
    requestedById: '3',
    requestedByName: 'Emma Rodriguez',
    requestedByOrg: 'Internal',
    submittedDate: '2026-01-25T10:00:00Z',
    dueDate: '2026-01-28T00:00:00Z',
    status: 'new',
    ownerId: '1',
    relatedEntityType: 'internal',
    relatedEntityId: 'int1',
    relatedEntityName: 'Internal Operations',
    comments: [],
    activityLog: sampleRequestActivity.slice(0, 1),
  },
  {
    id: 'req-6',
    requestType: 'employee',
    category: 'access',
    subject: 'Request access to client AWS account',
    description: 'Need access to TechVenture Labs AWS account to debug production issue. Require admin access to EC2 and RDS.',
    requestedById: '4',
    requestedByName: 'David Kim',
    requestedByOrg: 'Internal',
    submittedDate: '2026-01-26T08:00:00Z',
    dueDate: '2026-01-26T00:00:00Z',
    status: 'in-review',
    ownerId: '1',
    relatedEntityType: 'client',
    relatedEntityId: 'c1',
    relatedEntityName: 'TechVenture Labs',
    comments: sampleRequestComments,
    activityLog: sampleRequestActivity,
  },
  {
    id: 'req-7',
    requestType: 'employee',
    category: 'other',
    subject: 'Update emergency contact information',
    description: 'Need to update my emergency contact details in the HR system.',
    requestedById: '6',
    requestedByName: 'Michael Torres',
    requestedByOrg: 'Internal',
    submittedDate: '2026-01-23T12:00:00Z',
    status: 'fulfilled',
    ownerId: '7',
    relatedEntityType: 'internal',
    relatedEntityId: 'int1',
    relatedEntityName: 'Internal Operations',
    comments: [],
    activityLog: [...sampleRequestActivity, {
      id: 'ra4',
      userId: '7',
      action: 'fulfilled',
      timestamp: '2026-01-24T15:00:00Z',
    }],
  },

  // Freelancer Requests
  {
    id: 'req-8',
    requestType: 'freelancer',
    category: 'payment',
    subject: 'Invoice #INV-2026-0018 - Payment status inquiry',
    description: 'Submitted invoice 2 weeks ago but haven\'t received payment confirmation. Can you please check the status?',
    requestedById: 'ext-5',
    requestedByName: 'Alex Thompson',
    requestedByOrg: 'Independent Contractor',
    submittedDate: '2026-01-24T09:00:00Z',
    dueDate: '2026-01-27T00:00:00Z',
    status: 'in-review',
    ownerId: '7',
    relatedEntityType: 'project',
    relatedEntityId: 'p3',
    relatedEntityName: 'Mobile App Redesign',
    comments: sampleRequestComments,
    activityLog: sampleRequestActivity,
  },
  {
    id: 'req-9',
    requestType: 'freelancer',
    category: 'support',
    subject: 'Clarification on project requirements',
    description: 'Need clarification on the authentication flow requirements mentioned in the spec document. Section 3.2 is unclear.',
    requestedById: 'ext-6',
    requestedByName: 'Nina Patel',
    requestedByOrg: 'Design Contractor',
    submittedDate: '2026-01-25T14:00:00Z',
    dueDate: '2026-01-28T00:00:00Z',
    status: 'new',
    ownerId: '3',
    relatedEntityType: 'project',
    relatedEntityId: 'p2',
    relatedEntityName: 'AI Platform Development',
    comments: [],
    activityLog: sampleRequestActivity.slice(0, 1),
  },

  // Internal Requests
  {
    id: 'req-10',
    requestType: 'internal',
    category: 'other',
    subject: 'New laptop request - Current one failing',
    description: 'My current laptop has been freezing frequently. IT confirmed hardware failure. Need replacement urgently.',
    requestedById: '2',
    requestedByName: 'Marcus Johnson',
    requestedByOrg: 'Internal',
    submittedDate: '2026-01-21T10:00:00Z',
    status: 'approved',
    ownerId: '1',
    relatedEntityType: 'internal',
    relatedEntityId: 'int1',
    relatedEntityName: 'Internal Operations',
    comments: sampleRequestComments,
    activityLog: [...sampleRequestActivity, {
      id: 'ra5',
      userId: '1',
      action: 'approved',
      timestamp: '2026-01-22T14:00:00Z',
      details: 'Approved - MacBook Pro 16" ordered',
    }],
  },

  // More client requests
  {
    id: 'req-11',
    requestType: 'client',
    category: 'new-talent',
    subject: 'Urgent: Frontend developer needed for Q1 deadline',
    description: 'Project deadline moved up. Need an experienced React developer to join immediately.',
    requestedById: 'ext-7',
    requestedByName: 'Robert Davis',
    requestedByOrg: 'Quantum Systems',
    submittedDate: '2026-01-26T07:00:00Z',
    dueDate: '2026-01-30T00:00:00Z',
    status: 'new',
    ownerId: '5',
    relatedEntityType: 'project',
    relatedEntityId: 'p4',
    relatedEntityName: 'Data Analytics Dashboard',
    comments: [],
    activityLog: sampleRequestActivity.slice(0, 1),
  },

  // Rejected request
  {
    id: 'req-12',
    requestType: 'employee',
    category: 'leave',
    subject: 'Extended Leave - 3 weeks in March',
    description: 'Requesting 3 weeks leave during our busiest project phase.',
    requestedById: '5',
    requestedByName: 'Lisa Park',
    requestedByOrg: 'Internal',
    submittedDate: '2026-01-20T14:00:00Z',
    status: 'rejected',
    ownerId: '1',
    relatedEntityType: 'internal',
    relatedEntityId: 'int1',
    relatedEntityName: 'Internal Operations',
    comments: [{
      id: 'rc-reject',
      userId: '1',
      text: 'Unfortunately we cannot approve leave during Q1 deadline. Can you reschedule for Q2?',
      timestamp: '2026-01-21T10:00:00Z',
      isInternal: false,
    }],
    activityLog: [...sampleRequestActivity, {
      id: 'ra6',
      userId: '1',
      action: 'rejected',
      timestamp: '2026-01-21T10:00:00Z',
      details: 'Conflicts with critical project timeline',
    }],
  },

  // Converted request
  {
    id: 'req-13',
    requestType: 'client',
    category: 'support',
    subject: 'Performance issues on production dashboard',
    description: 'Dashboard loading times have increased significantly over the past week. Users are complaining.',
    requestedById: 'ext-8',
    requestedByName: 'Jennifer Lee',
    requestedByOrg: 'Quantum Systems',
    submittedDate: '2026-01-22T11:00:00Z',
    status: 'converted',
    ownerId: '4',
    relatedEntityType: 'project',
    relatedEntityId: 'p4',
    relatedEntityName: 'Data Analytics Dashboard',
    comments: sampleRequestComments,
    activityLog: [...sampleRequestActivity, {
      id: 'ra7',
      userId: '4',
      action: 'converted_to_issue',
      timestamp: '2026-01-22T15:00:00Z',
      details: 'Created issue #i7',
    }],
    convertedTo: {
      type: 'issue',
      id: 'i7',
    },
  },

  {
    id: 'req-14',
    requestType: 'freelancer',
    category: 'other',
    subject: 'Contract renewal discussion',
    description: 'Current contract ends Feb 28. Would like to discuss renewal terms and rate adjustment.',
    requestedById: 'ext-9',
    requestedByName: 'Carlos Rodriguez',
    requestedByOrg: 'DevOps Contractor',
    submittedDate: '2026-01-23T16:00:00Z',
    dueDate: '2026-02-10T00:00:00Z',
    status: 'in-review',
    ownerId: '1',
    relatedEntityType: 'project',
    relatedEntityId: 'p8',
    relatedEntityName: 'DevOps Automation',
    comments: sampleRequestComments,
    activityLog: sampleRequestActivity,
  },

  {
    id: 'req-15',
    requestType: 'client',
    category: 'change-request',
    subject: 'Add GDPR compliance features to platform',
    description: 'Need to add comprehensive GDPR compliance features including data export, deletion, and consent management.',
    requestedById: 'ext-10',
    requestedByName: 'Hans Mueller',
    requestedByOrg: 'Stellar Enterprises',
    submittedDate: '2026-01-19T13:00:00Z',
    dueDate: '2026-02-05T00:00:00Z',
    status: 'approved',
    ownerId: '1',
    relatedEntityType: 'project',
    relatedEntityId: 'p6',
    relatedEntityName: 'E-commerce Platform',
    comments: sampleRequestComments,
    activityLog: [...sampleRequestActivity, {
      id: 'ra8',
      userId: '1',
      action: 'approved',
      timestamp: '2026-01-20T10:00:00Z',
      details: 'Approved - Will create project scope document',
    }],
  },
];
